### ISSUE TITLE
doesn't work with C to C.

### ISSUE THREAD

**Issue by yangdigi** [ktec-hq/MiniUSB2C#1]
Need to add 5.1K resistor  between CC1 an d GND.  I will test it later.

**Comment by yangdigi** [comment]
yes. 5.1k pull down is necessary for cc1 and cc2.

**Comment by winterNebs** [comment]
Hi, Sorry to bother you on such an old project, for the 2 5.1k pull down resistors, is there any way to add them with this board? Or would that require modification. Thanks!
